# Generated by Django 4.2.1 on 2023-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villain',
            old_name='birth',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='villain',
            name='character_enemies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villain',
            name='powers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villain',
            name='weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villain',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
