# Generated by Django 4.2.1 on 2023-11-20 19:50

from django.db import migrations, models
import villains.models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0002_rename_birth_villain_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='image_screen_large_url',
            field=models.ImageField(blank=True, null=True, upload_to=villains.models.upload_to),
        ),
    ]
