# Generated by Django 4.2.1 on 2023-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0003_villain_image_screen_large_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='character_enemies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='villain',
            name='powers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='villain',
            name='weaknesses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
