# Generated by Django 4.2.1 on 2023-11-24 10:46

from django.db import migrations, models
import villains.models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0004_alter_villain_character_enemies_alter_villain_powers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='image_screen_large_url',
            field=models.ImageField(blank=True, null=True, upload_to=villains.models.upload_to_screen_url),
        ),
        migrations.AlterField(
            model_name='villain',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=villains.models.upload_to_images),
        ),
        migrations.AlterField(
            model_name='villain',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
