# Generated by Django 4.2.1 on 2023-10-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_alter_hero_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
