# Generated by Django 4.2.1 on 2023-10-31 23:48

from django.db import migrations, models
import heroes.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_hero_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=heroes.models.upload_to),
        ),
    ]
