# Generated by Django 4.2.1 on 2023-11-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
        ('heroes', '0004_alter_hero_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='villain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villains.villain'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Villain',
        ),
    ]
