# Generated by Django 4.2.1 on 2023-11-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_alter_fight_villain_alter_hero_age_delete_villain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
