# Generated by Django 4.2.1 on 2023-11-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_alter_fight_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sponsor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='origin',
        ),
        migrations.AddField(
            model_name='hero',
            name='sponsors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
