# Generated by Django 4.2.1 on 2023-11-10 16:25

from django.db import migrations, models
import heroes.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0013_sponsor_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='image_screen_large_url',
            field=models.ImageField(blank=True, null=True, upload_to=heroes.models.upload_to),
        ),
    ]
