# Generated by Django 4.2.1 on 2023-11-10 16:44

from django.db import migrations, models
import heroes.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0015_remove_sponsor_image_screen_large_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_screen_large_url',
            field=models.ImageField(blank=True, null=True, upload_to=heroes.models.upload_to_2),
        ),
    ]
