# Generated by Django 4.2.1 on 2023-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0018_alter_sponsor_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
