# Generated by Django 4.2.1 on 2023-11-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0020_rename_event_schedule_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
