# Generated by Django 4.2.1 on 2023-11-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0021_schedule_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
