# Generated by Django 4.2.1 on 2023-11-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0022_schedule_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='character_friends',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hero',
            name='powers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
