# Generated by Django 4.2.1 on 2023-11-24 05:21

from django.db import migrations, models
import heroes.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0023_alter_hero_character_friends_alter_hero_powers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_screen_large_url',
            field=models.ImageField(blank=True, null=True, upload_to=heroes.models.upload_to_screen_url),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=heroes.models.upload_to_images),
        ),
    ]
